version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-user:/var/lib/postgresql/data

  postgres-auction:
    image: postgres:16
    environment:
      POSTGRES_DB: auctiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata-auction:/var/lib/postgresql/data

  postgres-bid:
    image: postgres:16
    environment:
      POSTGRES_DB: biddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - pgdata-bid:/var/lib/postgresql/data

  postgres-payment:
    image: postgres:16
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata-payment:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - postgres-user

  auction-service:
    build: ./auction-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-auction
      - user-service
      - bid-service

  bid-service:
    build: ./bid-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres-bid
      - user-service

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres-payment
      - user-service
      - auction-service
      - bid-service

volumes:
  pgdata-user:
  pgdata-auction:
  pgdata-bid:
  pgdata-payment:
