apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-service
  labels:
    app: bid-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bid-service
  template:
    metadata:
      labels:
        app: bid-service
    spec:
      containers:
        - name: bid-service
          image: bid-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-bid:5432/biddb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SERVICES_USER_URL
              value: http://user-service:8081
            - name: SERVICES_AUCTION_URL
              value: http://auction-service:8082
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: bid-service
spec:
  selector:
    app: bid-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
